security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # /api/users/my endpoint'iga POST orqali murojaat qilinganda - token so'ralmasin
        user_create:
            pattern: ^/api/users/my$
            methods:
                - post
            security: false

        main:
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/users/auth
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

    access_control:
        - { path: ^/api/.+, roles: IS_AUTHENTICATED_FULLY}
        - { path: ^/api, roles: PUBLIC_ACCESS}








#security:
#    password_hashers:
#        App\Entity\User: 'auto'
#
#    providers:
#        app_user_provider:
#            entity:
#                class: App\Entity\User
#                property: email
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern: ^/api/users/auth$
#            stateless: true
#            json_login:
#                check_path: /api/users/auth
#                username_path: email
#                password_path: password
#                success_handler: lexik_jwt_authentication.handler.authentication_success
#                failure_handler: lexik_jwt_authentication.handler.authentication_failure
#
#        api:
#            pattern: ^/api
#            stateless: true
#            provider: app_user_provider
#            jwt: ~
#
##    access_control:
##        - { path: ^/api/users/my$, roles: PUBLIC_ACCESS }
##        - { path: ^/api/users/auth$, roles: PUBLIC_ACCESS }
##        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
#
#    access_control:
#             - { path: ^/api/.+, roles: IS_AUTHENTICATED_FULLY }
#             - { path: ^/api, roles: PUBLIC_ACCESS }
#
##security:
##    password_hashers:
##        App\Entity\User: 'auto'
##
##    providers:
##        app_user_provider:
##            entity:
##                class: App\Entity\User
##                property: email
##
##    firewalls:
##        dev:
##            pattern: ^/(_(profiler|wdt)|css|images|js)/
##            security: false
##
##        # /api/users/my endpoint'iga POST orqali murojaat qilinganda - token so'ralmasin
##        user_create:
##            pattern: ^/api/users/my$
##            methods:
##                - post
##            security: false
##
##        main:
##            stateless: true
##            provider: app_user_provider
##            json_login:
##                check_path: /api/users/auth
##                username_path: email
##                password_path: password
##                success_handler: lexik_jwt_authentication.handler.authentication_success
##                failure_handler: lexik_jwt_authentication.handler.authentication_failure
##            jwt: ~
##
##    access_control:
##        - { path: ^/api/.+, roles: IS_AUTHENTICATED_FULLY}
##        - { path: ^/api, roles: PUBLIC_ACCESS}
#
#
